[package]
name = "AutomationTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19" # Chrono Time, makes my job easier
open = "2.0.2"
